apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-1
  # namespace: default
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx
    ports:
      - containerPort: 80
        protocol: TCP
