apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
  # namespace: default
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 60
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hellow
            image: busybox
            args:
            - /bin/sh
            - -c
            - data; echo "Hello World"
          restartPolicy: OnFailure
