apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-3
  namespace: default
  labels:
    backend: go
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx
    ports:
      - containerPort: 80
        protocol: TCP