# kubectl -n default create secret generic test --from-literal=TEST_KEY="testvalue"
apiVersion: v1
kind: Secret
metadata:
  name: test
  # namespace: default
data:
  TEST_KEY: dGVzdHZhbHVl
type: Opaque

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-secret
  # namespace: default
  labels:
    app: nginx
    backend: python
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx
    ports:
      - containerPort: 80
        protocol: TCP
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: secrets-volume
  volumes:
  - name: secrets-volume
    secret:
      secretName: test
      items:
      - key: TEST_KEY
        path: shared-secret
